version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: eurosafe_db
    environment:
      POSTGRES_DB: eurosafe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"  # External Port 5433 -> Internal Port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: